config/routes.rb
Rails.application.routes.draw do

    root "admin#index"
  
  resources :users 

  resources :anchor_logos do
    get :reset_filterrific, on: :collection
  end

  resources :ac_motors do
    get :reset_filterrific, on: :collection
  end

  resources :bearings do
    get :reset_filterrific, on: :collection
  end
  resources :greases do
    get :reset_filterrific, on: :collection
  end
  resources :brush_holders do
    get :reset_filterrific, on: :collection
  end
  resources :c_clips do
    get :reset_filterrific, on: :collection
  end
  resources :capacitors do
    get :reset_filterrific, on: :collection
  end
  resources :carbon_brushes do
    get :reset_filterrific, on: :collection
  end
  resources :connectors do
    get :reset_filterrific, on: :collection
  end
  resources :copperwires do
    get :reset_filterrific, on: :collection
  end
  resources :cord_clips do
    get :reset_filterrific, on: :collection
  end
  resources :cords do
    get :reset_filterrific, on: :collection
  end
  resources :grommets do
    get :reset_filterrific, on: :collection
  end
  resources :nuts do
    get :reset_filterrific, on: :collection
  end
  resources :plastic_materials do
    get :reset_filterrific, on: :collection
  end
  resources :screws do
    get :reset_filterrific, on: :collection
  end
  resources :spiral_springs do
    get :reset_filterrific, on: :collection
  end
  resources :springs do
    get :reset_filterrific, on: :collection
  end
  resources :washers do
    get :reset_filterrific, on: :collection
  end

  resources :anchor_logos
  resources :ac_motors
  resources :bearings
  resources :brush_holders
  resources :c_clips
  resources :capacitors
  resources :carbon_brushes
  resources :connectors
  resources :copperwires
  resources :cords
  resources :cord_clips
  resources :greases
  resources :grommets
  resources :nuts
  resources :plastic_materials
  resources :screws
  resources :spiral_springs
  resources :springs
  resources :washers

  resources :anchor_logo_imports
  resources :ac_motor_imports
  resources :bearing_imports
  resources :brush_holder_imports
  resources :c_clip_imports
  resources :capacitor_imports
  resources :carbon_brush_imports
  resources :connector_imports
  resources :copperwire_imports
  resources :cord_imports
  resources :cord_clip_imports
  resources :grease_imports
  resources :grommet_imports
  resources :nut_imports
  resources :plastic_material_imports
  resources :screw_imports
  resources :spiral_spring_imports
  resources :spring_imports
  resources :washer_imports

  resources :ac_motors, :anchor_logos, :bearings, :brush_holders, :c_clips, :capacitors,
            :carbon_brushes, :connectors, :copperwires, :cords, :cord_clips, :greases,
            :grommets, :nuts, :plastic_materials, :screws, :spiral_springs, :springs, :washers do
    member do
      patch :block
      patch :unblock
      patch :approve
      patch :release
      get   :needs_editing
      get   :correct
    end
  end

  
  get "superadmin/approval_by_superadmin"
  get "superadmin/create_by_superadmin"

  get "pending/index"
  get "admin" => "admin#index"

  resources :sessions
  controller :sessions do
    get '/login' => :new, :via => :get
    match '/login' => :create, :via => :post
    delete '/logout', to: 'sessions#destroy', as: :logout
    get 'change_details' => :change_details
    get 'update_details' => :update_details
    get 'show_details' => :show_details
  end

  get "profile/index"
  get "profile/edit"
end

app/controllers/springs_controller.rb
class SpringsController < ApplicationController
  before_action :set_spring, only: [:show, :edit, :update, :destroy]

  # GET /springs
  def index
    @filterrific = initialize_filterrific(
      Spring, 
      params[:filterrific],
      select_options: {
      sorted_by: Spring.options_for_sorted_by,
      with_partnumber: Spring.partnumbers_for_select,
      with_description: Spring.descriptions_for_select,
      with_spring_type: Spring.spring_types_for_select,
      with_material_dia: Spring.material_dias_for_select,
      with_mean_dia: Spring.mean_dias_for_select,
      with_free_length: Spring.free_lengths_for_select,
      with_no_of_active_coils: Spring.no_of_active_coilss_for_select,
      with_solid_length_max: Spring.solid_length_maxs_for_select,
      with_dimension_f1: Spring.dimension_f1s_for_select,
      with_dimension_l1: Spring.dimension_l1s_for_select,
      with_dimension_f2: Spring.dimension_f2s_for_select,
      with_dimension_l2: Spring.dimension_l2s_for_select,
      with_initial_load_nm: Spring.initial_load_nms_for_select,
      with_final_load_nm: Spring.final_load_nms_for_select,
      with_torque_arm_length: Spring.torque_arm_lengths_for_select,
      with_hook_length: Spring.hook_lengths_for_select,
      with_hook_arc_radius: Spring.hook_arc_radiuss_for_select,
      with_spring_constant: Spring.spring_constants_for_select,
      with_unit: Spring.units_for_select,
      with_supplier: Spring.suppliers_for_select,
      with_drawing_norm: Spring.drawing_norms_for_select,
      with_where_used_product: Spring.where_used_products_for_select,
      with_where_used_plant: Spring.where_used_plants_for_select,
      with_remark: Spring.remarks_for_select,
      with_reason: Spring.reasons_for_select,
    }) or return
    @springs = @filterrific.find.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  rescue_from ActiveRecord::RecordNotFound, with: :reset_filterrific

  # GET /springs/1
  def show
  end

  # GET /springs/new
  def new
    @spring = Spring.new
  end

  # GET /springs/1/edit
  def edit
    @object = Spring.find(params[:id])
    render 'shared/edit'
  end

  def correct
    @object = Spring.find(params[:id])
    render 'shared/correct'
  end


  # POST /springs
  def create
    @spring = Spring.new(spring_params)

    @spring.uploaded_by_section = session[:user_section]
    @spring.uploader_role = session[:user_role]
    @spring.uploader_name = session[:user_name]
    @spring.release_status = "pending"

    if @spring.save
      redirect_to @spring, notice: 'Spring was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /springs/1
  def update
    @spring = Spring.find(params[:id])
    if params[:to_needs_editing] # if update call from needs editing, set part status accordingly
      @spring.release_status = "needs editing"
    else
      @spring.release_status = "pending"
    end
    if @spring.update(spring_params)
      redirect_to @spring, notice: 'Spring was successfully updated.'
    else
      render :edit
    end
  end

  def approve
    @spring = Spring.find(params[:id])
    @spring.release_status = "approved draft"
    @spring.save
    respond_to do |format|
      format.html { redirect_to(springs_url) }
      format.xml  { head :ok }
    end
  end

  def release
    @spring = Spring.find(params[:id])
    @spring.release_status = "released"
    @spring.save
    respond_to do |format|
      format.html { redirect_to(springs_url) }
      format.xml  { head :ok }
    end
  end

   def block
    @spring = Spring.find(params[:id])
    @spring.release_status = "block"
    @spring.save
    respond_to do |format|
      format.html { redirect_to(springs_url) }
      format.xml  { head :ok }
    end
  end

  def unblock
    @spring = Spring.find(params[:id])
    @spring.release_status = "released"
    @spring.save
    respond_to do |format|
      format.html { redirect_to(springs_url) }
      format.xml  { head :ok }
    end
  end

  def needs_editing
    @object = Spring.find(params[:id])
    render 'shared/needs_editing'
  end

  # DELETE /springs/1
  def destroy
    @spring.destroy
    redirect_to springs_url, notice: 'Spring was successfully destroyed.'
  end

  def reset_filterrific
      # Clear session persistence
      session[:filterrific_springs] = nil
      # Redirect back to the index action for default filter settings.
      redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spring
      @spring = Spring.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def spring_params
      params.require(:spring).permit(:id, :partnumber, :description, :spring_type, :material_dia, 
        :mean_dia, :free_length, :no_of_active_coils, :solid_length_max, :dimension_f1, :dimension_l1, 
        :dimension_f2, :dimension_l2, :initial_load_nm, :final_load_nm, :torque_arm_length, :hook_length, 
        :hook_arc_radius, :spring_constant, :unit, :supplier, :drawing_norm, :where_used_product, 
        :where_used_plant, :remark, :release_status, 
        :need_to_edit_partnumber, :need_to_edit_description, :need_to_edit_spring_type, 
        :need_to_edit_material_dia, :need_to_edit_mean_dia, :need_to_edit_free_length, 
        :need_to_edit_no_of_active_coils, :need_to_edit_solid_length_max, :need_to_edit_dimension_f1, 
        :need_to_edit_dimension_l1, :need_to_edit_dimension_f2, :need_to_edit_dimension_l2, 
        :need_to_edit_initial_load_nm, :need_to_edit_final_load_nm, :need_to_edit_torque_arm_length, 
        :need_to_edit_hook_length, :need_to_edit_hook_arc_radius, :need_to_edit_spring_constant, 
        :need_to_edit_unit, :need_to_edit_supplier, :need_to_edit_drawing_norm, :need_to_edit_where_used_product, 
        :need_to_edit_where_used_plant, :need_to_edit_remark, :need_to_edit_reason,
        :reason)
    end
end

app/helpers/springs_helper.rb
module SpringsHelper
end

app/views/springs/_form.html.erb
<%= form_for(@spring) do |f| %>
  <% if @spring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spring.errors.count, "error") %> prohibited this spring from being saved:</h2>

      <ul>
      <% @spring.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :partnumber %><br>
    <%= f.text_field :partnumber %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :spring_type %><br>
    <%= f.text_field :spring_type %>
  </div>
  <div class="field">
    <%= f.label :material_dia %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :material_dia %>
  </div>
  <div class="field">
    <%= f.label :mean_dia %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :mean_dia %>
  </div>
  <div class="field">
    <%= f.label :free_length %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :free_length %>
  </div>
  <div class="field">
    <%= f.label :no_of_active_coils %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :no_of_active_coils %>
  </div>
  <div class="field">
    <%= f.label :solid_length_max %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :solid_length_max %>
  </div>
  <div class="field">
    <%= f.label :dimension_f1 %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :dimension_f1 %>
  </div>
  <div class="field">
    <%= f.label :dimension_l1 %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :dimension_l1 %>
  </div>
  <div class="field">
    <%= f.label :dimension_f2 %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :dimension_f2 %>
  </div>
  <div class="field">
    <%= f.label :dimension_l2 %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :dimension_l2 %>
  </div>
  <div class="field">
    <%= f.label :initial_load_nm %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :initial_load_nm %>
  </div>
  <div class="field">
    <%= f.label :final_load_nm %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :final_load_nm %>
  </div>
  <div class="field">
    <%= f.label :torque_arm_length %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :torque_arm_length %>
  </div>
  <div class="field">
    <%= f.label :hook_length %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :hook_length %>
  </div>
  <div class="field">
    <%= f.label :hook_arc_radius %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :hook_arc_radius %>
  </div>
  <div class="field">
    <%= f.label :spring_constant %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :spring_constant %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :drawing_norm %><br>
    <%= f.text_field :drawing_norm %>
  </div>
  <div class="field">
    <%= f.label :where_used_product %><br>
    <%= f.text_field :where_used_product %>
  </div>
  <div class="field">
    <%= f.label :where_used_plant %><br>
    <%= f.text_field :where_used_plant %>
  </div>
  <div class="field">
    <%= f.label :remark %><br>
    <%= f.text_field :remark %>
  </div>
  <br />
  <div class="field">
    <%= f.label :reason_for_submission? %><br />
    <%= f.text_field :reason %>
  </div>   
  <br />
  

  <% if session[:user_role] == "Normal" && @spring.uploader_name == nil || session[:user_role] == "Sectionhead" && @spring.uploader_name == nil %>
      <div class="field">
        <%= f.label :release_status %><br />
        <%= f.text_field :release_status, :value => "pending", :readonly => true %>
      </div>
  <% end %>
    
  <% if @spring.uploader_name != session[:user_name] && session[:user_role] != "Superadmin" %>
    <div class="actions">
      <%= f.submit 'Submit spring', :name => 'submit' %>
    </div>
  <% end %>

  <% if @spring.uploader_name == session[:user_name] || session[:user_role] == "Superadmin" %>
    <div class="actions">
      <%= f.submit 'Update spring', :name => 'create' %>
    </div>
  <% end %>
<% end %>

app/views/springs/_form_finalrelease.html.erb
<br />
<h2>This part is waiting to get released!</h2>
<br />

<p>
  <strong>Partnumber:</strong>
  <%= @spring.partnumber %>
</p>

<p>
  <strong>Description:</strong>
  <%= @spring.description %>
</p>

<p>
  <strong>Spring type:</strong>
  <%= @spring.spring_type %>
</p>

<p>
  <strong>Material dia:</strong>
  <%= @spring.material_dia %>
</p>

<p>
  <strong>Mean dia:</strong>
  <%= @spring.mean_dia %>
</p>

<p>
  <strong>Free length:</strong>
  <%= @spring.free_length %>
</p>

<p>
  <strong>No of active coils:</strong>
  <%= @spring.no_of_active_coils %>
</p>

<p>
  <strong>Solid length max:</strong>
  <%= @spring.solid_length_max %>
</p>

<p>
  <strong>Dimension f1:</strong>
  <%= @spring.dimension_f1 %>
</p>

<p>
  <strong>Dimension l1:</strong>
  <%= @spring.dimension_l1 %>
</p>

<p>
  <strong>Dimension f2:</strong>
  <%= @spring.dimension_f2 %>
</p>

<p>
  <strong>Dimension l2:</strong>
  <%= @spring.dimension_l2 %>
</p>

<p>
  <strong>Initial load nm:</strong>
  <%= @spring.initial_load_nm %>
</p>

<p>
  <strong>Final load nm:</strong>
  <%= @spring.final_load_nm %>
</p>

<p>
  <strong>Torque arm length:</strong>
  <%= @spring.torque_arm_length %>
</p>

<p>
  <strong>Hook length:</strong>
  <%= @spring.hook_length %>
</p>

<p>
  <strong>Hook arc radius:</strong>
  <%= @spring.hook_arc_radius %>
</p>

<p>
  <strong>Spring constant:</strong>
  <%= @spring.spring_constant %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @spring.unit %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @spring.supplier %>
</p>

<p>
  <strong>Drawing norm:</strong>
  <%= @spring.drawing_norm %>
</p>

<p>
  <strong>Where used product:</strong>
  <%= @spring.where_used_product %>
</p>

<p>
  <strong>Where used plant:</strong>
  <%= @spring.where_used_plant %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @spring.remark %>
</p>

<br />

<p>
    <b>Reason for submission:</b>
    <%= @spring.reason %>
  </p><br />

  <% if session[:user_role] == "Sectionhead" && @spring.uploader_role == "Normal" && @spring.release_status == "approved draft" && @spring.uploaded_by_section == session[:user_section] %> 

    <%= form_for(@spring) do |f| %>
        <% if @spring.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@spring.errors.count, "error") %> prohibited this spring from being saved:</h2>

            <ul>
            <% @spring.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <div class="field">
              <%= f.label :Status? %><br />
              <%= f.text_field :release_status, :value => "released", :readonly => true %>
          </div>
          
          <br />

          <div class="actions">
            <%= f.submit 'Release Spring', :name => 'create' %>
          </div>
      <% end %>
    <% end %>

app/views/springs/_list.html.erb
<div id="filterrific_results" %>
<div><%= page_entries_info springs %></div>

<table class="table table-hover">
  <tr class="active">
      <th class="text-center">Partnumber</th>
      <th class="text-center">Status</th>
      <th class="text-center">Description</th>
      <th class="text-center">Spring type</th>
      <th class="text-center">Material dia</th>
      <th class="text-center">Mean dia</th>
      <th class="text-center">Free length</th>
      <th class="text-center">No of active coils</th>
      <th class="text-center">Solid length max</th>
      <th class="text-center">Dimension f1</th>
      <th class="text-center">Dimension l1</th>
      <th class="text-center">Dimension f2</th>
      <th class="text-center">Dimension l2</th>
      <th class="text-center">Initial load nm</th>
      <th class="text-center">Final load nm</th>
      <th class="text-center">Torque arm length</th>
      <th class="text-center">Hook length</th>
      <th class="text-center">Hook arc radius</th>
      <th class="text-center">Spring constant</th>
      <th class="text-center">Unit</th>
      <th class="text-center">Supplier</th>
      <th class="text-center">Drawing norm</th>
      <th class="text-center">Where used product</th>
      <th class="text-center">Where used plant</th>
      <th class="text-center">Remark</th>
      <th class="text-center">Reason</th>
    </tr>

  <tbody>
    <% springs.each do |spring| %>
      <% if spring.release_status == "needs editing" && spring.uploader_name == session[:user_name] %>
        <tr class="danger">
      <% elsif spring.release_status == "pending" && session[:user_role] == "Sectionhead" && spring.uploader_role == "Normal" && spring.uploaded_by_section == session[:user_section] || session[:user_role] == "Departmenthead" && spring.uploader_role == "Sectionhead" && spring.release_status == "pending" %>
        <tr class="warning">
      <% elsif spring.release_status == "pending" || spring.release_status == "needs editing" %>
        <tr class="pending_parts">
      <% else %>
        <tr>
      <% end %>
        <td><%= link_to "#{spring.partnumber}", spring, method: :get %></td>
        <td><%= spring.release_status %></td>
        <td><%= spring.description %></td>
        <td><%= spring.spring_type %></td>
        <td><%= spring.material_dia %></td>
        <td><%= spring.mean_dia %></td>
        <td><%= spring.free_length %></td>
        <td><%= spring.no_of_active_coils %></td>
        <td><%= spring.solid_length_max %></td>
        <td><%= spring.dimension_f1 %></td>
        <td><%= spring.dimension_l1 %></td>
        <td><%= spring.dimension_f2 %></td>
        <td><%= spring.dimension_l2 %></td>
        <td><%= spring.initial_load_nm %></td>
        <td><%= spring.final_load_nm %></td>
        <td><%= spring.torque_arm_length %></td>
        <td><%= spring.hook_length %></td>
        <td><%= spring.hook_arc_radius %></td>
        <td><%= spring.spring_constant %></td>
        <td><%= spring.unit %></td>
        <td><%= spring.supplier %></td>
        <td><%= spring.drawing_norm %></td>
        <td><%= spring.where_used_product %></td>
        <td><%= spring.where_used_plant %></td>
        <td><%= spring.remark %></td>
        <td><%= spring.reason %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate springs %>
</div>

app/views/springs/index.html.erb
<h1>Listing springs</h1>

<% if flash[:warning] or flash[:notice] %>
  <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
    <%= flash[:warning] || flash[:notice] %>
  </div>

<% end %>

<div class="row">
  <%= form_for_filterrific @filterrific do |f| %>
     <span class="glyphicon glyphicon-search"></span> <%= f.text_field(:search_query, class: 'filterrific-periodically-observed') %>
     <button class="btn btn-default btn-xs" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <span class="glyphicon glyphicon-filter"></span>
  </button>
  <% end %>
</div>

<div class="row">
<div class="collapse" id="collapseExample">
  <%= render(
              partial: 'shared/filter',
              locals: { obj: Spring }) 
  %>
</div>

<%= render(
    partial: 'springs/list', 
    locals: { springs: @springs }) 
%>

<br />

<% if is_section_head? || is_normal? %>
  <%= button_to 'New Spring', new_spring_path, :method => :get, class: "btn btn-default" %>
<% elsif is_superadmin? %>
  <%= link_to "Mass Import", new_spring_import_path, class: "btn btn-default" %>
<% end %>

app/views/springs/index.js.erb
<% js = escape_javascript(
  render(partial: 'springs/list', locals: { springs: @springs })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/springs/new.html.erb
<h1>New spring</h1>

<%= render 'form' %>

app/views/springs/show.html.erb
<% if flash[:warning] or flash[:notice] %>
  <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
    <%= flash[:warning] || flash[:notice] %>
  </div>

<% end %>

 <%= part_status(@spring) %>

<p>
  <strong>Partnumber:</strong>
  <%= @spring.partnumber %>
</p>

<p>
  <strong>Description:</strong>
  <%= @spring.description %>
</p>

<p>
  <strong>Spring type:</strong>
  <%= @spring.spring_type %>
</p>

<p>
  <strong>Material dia:</strong>
  <%= @spring.material_dia %>
</p>

<p>
  <strong>Mean dia:</strong>
  <%= @spring.mean_dia %>
</p>

<p>
  <strong>Free length:</strong>
  <%= @spring.free_length %>
</p>

<p>
  <strong>No of active coils:</strong>
  <%= @spring.no_of_active_coils %>
</p>

<p>
  <strong>Solid length max:</strong>
  <%= @spring.solid_length_max %>
</p>

<p>
  <strong>Dimension f1:</strong>
  <%= @spring.dimension_f1 %>
</p>

<p>
  <strong>Dimension l1:</strong>
  <%= @spring.dimension_l1 %>
</p>

<p>
  <strong>Dimension f2:</strong>
  <%= @spring.dimension_f2 %>
</p>

<p>
  <strong>Dimension l2:</strong>
  <%= @spring.dimension_l2 %>
</p>

<p>
  <strong>Initial load nm:</strong>
  <%= @spring.initial_load_nm %>
</p>

<p>
  <strong>Final load nm:</strong>
  <%= @spring.final_load_nm %>
</p>

<p>
  <strong>Torque arm length:</strong>
  <%= @spring.torque_arm_length %>
</p>

<p>
  <strong>Hook length:</strong>
  <%= @spring.hook_length %>
</p>

<p>
  <strong>Hook arc radius:</strong>
  <%= @spring.hook_arc_radius %>
</p>

<p>
  <strong>Spring constant:</strong>
  <%= @spring.spring_constant %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @spring.unit %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @spring.supplier %>
</p>

<p>
  <strong>Drawing norm:</strong>
  <%= @spring.drawing_norm %>
</p>

<p>
  <strong>Where used product:</strong>
  <%= @spring.where_used_product %>
</p>

<p>
  <strong>Where used plant:</strong>
  <%= @spring.where_used_plant %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @spring.remark %>
</p>



<br />

<p>
    <b>Reason for submission:</b>
    <%= @spring.reason %>
  </p><br />

  <p>
    <b>Submitted by:</b>
    <%= @spring.uploader_name %>
  </p>

  <p>
    <b>Created at:</b>
    <%= @spring.created_at %>
  </p>

  <p>
    <b>Last updated at:</b>
    <%= @spring.updated_at %>
  </p>

<%= render 'shared/show_actions', :object => @spring %>