config/routes.rb
Rails.application.routes.draw do

    root "admin#index"
  
  resources :users 

  resources :anchor_logos do
    get :reset_filterrific, on: :collection
  end

  resources :ac_motors do
    get :reset_filterrific, on: :collection
  end

  resources :bearings do
    get :reset_filterrific, on: :collection
  end
  resources :greases do
    get :reset_filterrific, on: :collection
  end
  resources :brush_holders do
    get :reset_filterrific, on: :collection
  end
  resources :c_clips do
    get :reset_filterrific, on: :collection
  end
  resources :capacitors do
    get :reset_filterrific, on: :collection
  end
  resources :carbon_brushes do
    get :reset_filterrific, on: :collection
  end
  resources :connectors do
    get :reset_filterrific, on: :collection
  end
  resources :copperwires do
    get :reset_filterrific, on: :collection
  end
  resources :cord_clips do
    get :reset_filterrific, on: :collection
  end
  resources :cords do
    get :reset_filterrific, on: :collection
  end
  resources :grommets do
    get :reset_filterrific, on: :collection
  end
  resources :nuts do
    get :reset_filterrific, on: :collection
  end
  resources :plastic_materials do
    get :reset_filterrific, on: :collection
  end
  resources :screws do
    get :reset_filterrific, on: :collection
  end
  resources :spiral_springs do
    get :reset_filterrific, on: :collection
  end
  resources :springs do
    get :reset_filterrific, on: :collection
  end
  resources :washers do
    get :reset_filterrific, on: :collection
  end

  resources :anchor_logos
  resources :ac_motors
  resources :bearings
  resources :brush_holders
  resources :c_clips
  resources :capacitors
  resources :carbon_brushes
  resources :connectors
  resources :copperwires
  resources :cords
  resources :cord_clips
  resources :greases
  resources :grommets
  resources :nuts
  resources :plastic_materials
  resources :screws
  resources :spiral_springs
  resources :springs
  resources :washers

  resources :anchor_logo_imports
  resources :ac_motor_imports
  resources :bearing_imports
  resources :brush_holder_imports
  resources :c_clip_imports
  resources :capacitor_imports
  resources :carbon_brush_imports
  resources :connector_imports
  resources :copperwire_imports
  resources :cord_imports
  resources :cord_clip_imports
  resources :grease_imports
  resources :grommet_imports
  resources :nut_imports
  resources :plastic_material_imports
  resources :screw_imports
  resources :spiral_spring_imports
  resources :spring_imports
  resources :washer_imports

  resources :ac_motors, :anchor_logos, :bearings, :brush_holders, :c_clips, :capacitors,
            :carbon_brushes, :connectors, :copperwires, :cords, :cord_clips, :greases,
            :grommets, :nuts, :plastic_materials, :screws, :spiral_springs, :springs, :washers do
    member do
      patch :block
      patch :unblock
      patch :approve
      patch :release
      get   :needs_editing
      get   :correct
    end
  end

  
  get "superadmin/approval_by_superadmin"
  get "superadmin/create_by_superadmin"

  get "pending/index"
  get "admin" => "admin#index"

  resources :sessions
  controller :sessions do
    get '/login' => :new, :via => :get
    match '/login' => :create, :via => :post
    delete '/logout', to: 'sessions#destroy', as: :logout
    get 'change_details' => :change_details
    get 'update_details' => :update_details
    get 'show_details' => :show_details
  end

  get "profile/index"
  get "profile/edit"
end

app/models/brush_holder.rb
class BrushHolder < ActiveRecord::Base
   include ValidateMethods
    include CommonConstants
  	after_initialize :init

  	self.per_page = 15

  	def self.search(query)
  		where('release_status LIKE ? or partnumber LIKE ? or description LIKE ? 
        or brush_holder_type LIKE ? or material LIKE ? or drawing_norm LIKE ? 
        or corresponding_carbon_brush LIKE ? or supplier LIKE ? or where_used_product LIKE ? 
        or where_used_plant LIKE ? or reason LIKE ?',
  		"%#{query}%", "%#{query}%", "%#{query}%" , "%#{query}%", "%#{query}%" ,
       "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")
	end

	def self.to_csv(options = {})
  	CSV.generate(options) do |csv|
  	  csv << column_names
  	  all.each do |brush_holder|
  	  	csv << brush_holder.attributes.values_at(*column_names)
  	  end
  	end
  end

  def self.accessible_attributes
    ["id","partnumber","description","brush_holder_type","material",
    	"drawing_norm","corresponding_carbon_brush","supplier",
    	"where_used_product","where_used_plant","reason"]
  end

  def init 
    self.release_status ||= "released"
  end

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :search_query,
      :sorted_by,
      :with_partnumber,
      :with_description,
      :with_brush_holder_type,
      :with_material,
      :with_drawing_norm,
      :with_corresponding_carbon_brush,
      :with_supplier,
      :with_where_used_product,
      :with_where_used_plant,
      :with_reason,
    ]
    )

  def self.options_for_sorted_by
      [
        ['Submission date (newest first)', 'created_at_desc'],
        ['Submission date (oldest first)', 'created_at_asc'],
        ['partnumber (larger number first)','partnumber_at_desc'],
        ['partnumber (smaller number first)','partnumber_at_asc'],
      ]
  end

  def self.partnumbers_for_select
    order('LOWER(partnumber)').map { |e| [e.partnumber, e.partnumber] }.uniq
  end

  def self.descriptions_for_select
    order('LOWER(description)').map { |e| [e.description, e.description] }.uniq
  end

  def self.brush_holder_types_for_select
    order('LOWER(brush_holder_type)').map { |e| [e.brush_holder_type, e.brush_holder_type] }.uniq
  end

  def self.materials_for_select
    order('LOWER(material)').map { |e| [e.material, e.material] }.uniq
  end

  def self.drawing_norms_for_select
    order('LOWER(drawing_norm)').map { |e| [e.drawing_norm, e.drawing_norm] }.uniq
  end

  def self.corresponding_carbon_brushs_for_select
    order('LOWER(corresponding_carbon_brush)').map { |e| [e.corresponding_carbon_brush, e.corresponding_carbon_brush] }.uniq
  end

  def self.suppliers_for_select
    order('LOWER(supplier)').map { |e| [e.supplier, e.supplier] }.uniq
  end

  def self.where_used_products_for_select
    order('LOWER(where_used_product)').map { |e| [e.where_used_product, e.where_used_product] }.uniq
  end

  def self.where_used_plants_for_select
    order('LOWER(where_used_plant)').map { |e| [e.where_used_plant, e.where_used_plant] }.uniq
  end

  def self.reasons_for_select
    order('LOWER(reason)').map { |e| [e.reason, e.reason] }.uniq
  end

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
    order("brush_holders.created_at #{ direction }")
    when /^partnumber_/
    order("LOWER(brush_holders.partnumber) #{ direction }")
    when /^description_/
    order("LOWER(brush_holders.description) #{ direction }")
    when /^brush_holder_type_/
    order("LOWER(brush_holders.brush_holder_type) #{ direction }")
    when /^material_/
    order("LOWER(brush_holders.material) #{ direction }")
    when /^drawing_norm_/
    order("LOWER(brush_holders.drawing_norm) #{ direction }")
  when /^corresponding_carbon_brush_/
    order("LOWER(brush_holders.corresponding_carbon_brush) #{ direction }")
    when /^supplier_/
    order("LOWER(brush_holders.supplier) #{ direction }")
    when /^where_used_product_/
    order("LOWER(brush_holders.where_used_product) #{ direction }")
  when /^where_used_plant_/
    order("LOWER(brush_holders.where_used_plant) #{ direction }")
  when /^reason_/
    order("LOWER(brush_holders.reason) #{ direction }")
  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end
    
  }
scope :with_partnumber, lambda { |partnumbers| where(partnumber: [*partnumbers])}
scope :with_description, lambda { |descriptions| where(description: [*descriptions])}
scope :with_brush_holder_type, lambda { |brush_holder_types| where(brush_holder_type: [*brush_holder_types])}
scope :with_material, lambda { |materials| where(material: [*materials])}
scope :with_drawing_norm, lambda { |drawing_norms| where(drawing_norm: [*drawing_norms])}
scope :with_corresponding_carbon_brush, lambda { |corresponding_carbon_brushs| where(corresponding_carbon_brush: [*corresponding_carbon_brushs])}
scope :with_supplier, lambda { |suppliers| where(supplier: [*suppliers])}
scope :with_where_used_product, lambda { |where_used_products| where(where_used_product: [*where_used_products])}
scope :with_where_used_plant, lambda { |where_used_plants| where(where_used_plant: [*where_used_plants])}
scope :with_reason, lambda { |reasons| where(reason: [*reasons])}


scope :search_query, lambda { |query|
  return nil  if query.blank?
  # condition query, parse into individual keywords
  #terms = query.downcase.split(/\s+/)
  if query.is_a? String
    terms = query.downcase
    terms = (terms.gsub('*', '%') + '%').gsub(/%+/, '%')
  else
    terms =  query
  end

  # replace "*" with "%" for wildcard searches,
  # append '%', remove duplicate '%'s
  # terms = terms.map { |e|
  #   (e.gsub('*', '%') + '%').gsub(/%+/, '%')
  # }
  # configure number of OR conditions for provision
  # of interpolation arguments. Adjust this if you
  # change the number of OR conditions.
  # num_or_conds = 7
  where("LOWER(brush_holders.partnumber) LIKE ? OR LOWER(brush_holders.description) LIKE ? OR LOWER(brush_holders.brush_holder_type) LIKE ?
         OR LOWER(brush_holders.material) LIKE ? OR LOWER(brush_holders.drawing_norm) LIKE ? OR LOWER(brush_holders.corresponding_carbon_brush) LIKE ?
          OR LOWER(brush_holders.supplier) LIKE ? OR LOWER(brush_holders.where_used_product) LIKE ? OR LOWER(brush_holders.where_used_plant) LIKE ?
          OR LOWER(brush_holders.reason) LIKE ? ",
          terms, terms, terms, terms, terms, terms, terms, terms, terms, terms)
}
end

app/controllers/brush_holders_controller.rb
class BrushHoldersController < ApplicationController
  # GET /brush_holders
  # GET /brush_holders.xml
  def index
    @filterrific = initialize_filterrific(
      BrushHolder, 
      params[:filterrific],
      select_options: {
      sorted_by: BrushHolder.options_for_sorted_by,
      with_partnumber: BrushHolder.partnumbers_for_select,
      with_description: BrushHolder.descriptions_for_select,
      with_brush_holder_type: BrushHolder.brush_holder_types_for_select,
      with_material: BrushHolder.materials_for_select,
      with_drawing_norm: BrushHolder.drawing_norms_for_select,
      with_corresponding_carbon_brush: BrushHolder.corresponding_carbon_brushs_for_select,
      with_supplier: BrushHolder.suppliers_for_select,
      with_where_used_product: BrushHolder.where_used_products_for_select,
      with_where_used_plant: BrushHolder.where_used_plants_for_select,
      with_reason: BrushHolder.reasons_for_select
    }) or return
    @brush_holders = @filterrific.find.page(params[:page]) 
     respond_to do |format|
      format.html
      format.js
    end
  end

  rescue_from ActiveRecord::RecordNotFound, with: :reset_filterrific

  # GET /brush_holders/1
  # GET /brush_holders/1.xml
  def show
    @brush_holder = BrushHolder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @brush_holder }
    end
  end

  # GET /brush_holders/new
  # GET /brush_holders/new.xml
  def new
    @brush_holder = BrushHolder.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @brush_holder }
    end
  end

  # GET /brush_holders/1/edit
  def edit
    @brush_holder = BrushHolder.find(params[:id])
    @object = BrushHolder.find(params[:id])
    render 'shared/edit'
  end

  def correct
    @object = BrushHolder.find(params[:id])
    render 'shared/correct'
  end

  # POST /brush_holders
  # POST /brush_holders.xml
  def create
    @brush_holder = BrushHolder.new(brush_holder_params)

    @brush_holder.uploaded_by_section = session[:user_section]
    @brush_holder.uploader_role = session[:user_role]
    @brush_holder.uploader_name = session[:user_name]
    @brush_holder.release_status = "pending"

    respond_to do |format|
      if @brush_holder.save
        format.html { redirect_to(@brush_holder, :notice => 'Brush holder was successfully created.') }
        format.xml  { render :xml => @brush_holder, :status => :created, :location => @brush_holder }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @brush_holder.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /brush_holders/1
  # PUT /brush_holders/1.xml
  def update
    @brush_holder = BrushHolder.find(params[:id])
    if params[:to_needs_editing] # if update call from needs editing, set part status accordingly
      @brush_holder.release_status = "needs editing"
    else
      @brush_holder.release_status = "pending"
    end
    respond_to do |format|
      if @brush_holder.update_attributes(brush_holder_params)
        format.html { redirect_to(@brush_holder, :notice => 'Brush holder was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @brush_holder.errors, :status => :unprocessable_entity }
      end
    end
  end

  def approve
    @brush_holder = BrushHolder.find(params[:id])
    @brush_holder.release_status = "approved draft"
    @brush_holder.save
    respond_to do |format|
      format.html { redirect_to(brush_holders_url) }
      format.xml  { head :ok }
    end
  end

  def release
    @brush_holder = BrushHolder.find(params[:id])
    @brush_holder.release_status = "released"
    @brush_holder.save
    respond_to do |format|
      format.html { redirect_to(brush_holders_url) }
      format.xml  { head :ok }
    end
  end


   def block
    @brush_holder = BrushHolder.find(params[:id])
    @brush_holder.release_status = "block"
    @brush_holder.save
    respond_to do |format|
      format.html { redirect_to(brush_holders_url) }
      format.xml  { head :ok }
    end
  end

  def unblock
    @brush_holder = BrushHolder.find(params[:id])
    @brush_holder.release_status = "released"
    @brush_holder.save
    respond_to do |format|
      format.html { redirect_to(brush_holders_url) }
      format.xml  { head :ok }
    end
  end

  def needs_editing
    @object = BrushHolder.find(params[:id])
    render 'shared/needs_editing'
  end
  # DELETE /brush_holders/1
  # DELETE /brush_holders/1.xml
  def destroy
    @brush_holder = BrushHolder.find(params[:id])
    @brush_holder.destroy

    respond_to do |format|
      format.html { redirect_to(brush_holders_url) }
      format.xml  { head :ok }
    end
  end

  def reset_filterrific
      # Clear session persistence
      session[:filterrific_brush_holders] = nil
      # Redirect back to the index action for default filter settings.
      redirect_to action: :index
  end
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_brush_holder
      @brush_holder = BrushHolder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brush_holder_params
      params.require(:brush_holder).permit(:id, :partnumber, :description, :brush_holder_type, 
        :material, :drawing_norm, :corresponding_carbon_brush, :supplier, :where_used_product, 
        :where_used_plant, :release_status,
        :need_to_edit_partnumber, :need_to_edit_description, :need_to_edit_brush_holder_type, 
        :need_to_edit_material, :need_to_edit_drawing_norm, :need_to_edit_corresponding_carbon_brush, 
        :need_to_edit_supplier, :need_to_edit_where_used_product, :need_to_edit_where_used_plant,
        :reason, :need_to_edit_reason)
    end

app/helpers/brush_holders_helper.rb
module BrushHoldersHelper
end

app/views/brush_holders/_form.html.erb
<%= form_for(@brush_holder) do |f| %>
  <% if @brush_holder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brush_holder.errors.count, "error") %> prohibited this brush_holder from being saved:</h2>

      <ul>
      <% @brush_holder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :partnumber %><br />
    <%= f.text_field :partnumber %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :brush_holder_type %><br />
    <%= f.text_field :brush_holder_type %>
  </div>
  <div class="field">
    <%= f.label :material %><br />
    <%= f.text_field :material %>
  </div>
  <div class="field">
    <%= f.label :drawing_norm %><br />
    <%= f.text_field :drawing_norm %>
  </div>
  <div class="field">
    <%= f.label :corresponding_carbon_brush %><br />
    <%= f.text_field :corresponding_carbon_brush %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br />
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :where_used_product %><br />
    <%= f.text_field :where_used_product %>
  </div>
  <div class="field">
    <%= f.label :where_used_plant %><br />
    <%= f.text_field :where_used_plant %>
  </div>
  <br />
  <div class="field">
    <%= f.label :reason_for_submission? %><br />
    <%= f.text_field :reason %>
  </div>   
  <br />
  

  <% if session[:user_role] == "Normal" && @brush_holder.uploader_name == nil || session[:user_role] == "Sectionhead" && @brush_holder.uploader_name == nil %>
      <div class="field">
        <%= f.label :release_status %><br />
        <%= f.text_field :release_status, :value => "pending", :readonly => true %>
      </div>
  <% end %>
    
  <% if @brush_holder.uploader_name != session[:user_name] && session[:user_role] != "Superadmin" %>
    <div class="actions">
      <%= f.submit 'Submit Brush holder', :name => 'submit' %>
    </div>
  <% end %>

  <% if @brush_holder.uploader_name == session[:user_name] || session[:user_role] == "Superadmin" %>
    <div class="actions">
      <%= f.submit 'Update Brush holder', :name => 'create' %>
    </div>
  <% end %>
<% end %>

app/views/brush_holders/_form_finalrelease.html.erb
<br />
<h2>This part is waiting to get released!</h2>
<br />
<p>
  <b>Partnumber:</b>
  <%= @brush_holder.partnumber %>
</p>

<p>
  <b>Description:</b>
  <%= @brush_holder.description %>
</p>

<p>
  <b>Brush holder type:</b>
  <%= @brush_holder.brush_holder_type %>
</p>

<p>
  <b>Material:</b>
  <%= @brush_holder.material %>
</p>

<p>
  <b>Drawing norm:</b>
  <%= @brush_holder.drawing_norm %>
</p>

<p>
  <b>Corresponding carbon brush:</b>
  <%= @brush_holder.corresponding_carbon_brush %>
</p>

<p>
  <b>Supplier:</b>
  <%= @brush_holder.supplier %>
</p>

<p>
  <b>Where used product:</b>
  <%= @brush_holder.where_used_product %>
</p>

<p>
  <b>Where used plant:</b>
  <%= @brush_holder.where_used_plant %>
</p>
<p>
    <b>Reason for submission:</b>
    <%= @brush_holder.reason %>
  </p><br />

<% if session[:user_role] == "Sectionhead" && @brush_holder.uploader_role == "Normal" && @brush_holder.release_status == "approved draft" && @brush_holder.uploaded_by_section == session[:user_section] %> 

    <%= form_for(@brush_holder) do |f| %>
        <% if @brush_holder.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@brush_holder.errors.count, "error") %> prohibited this brush holder from being saved:</h2>

            <ul>
            <% @brush_holder.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <div class="field">
              <%= f.label :Status? %><br />
              <%= f.text_field :release_status, :value => "released", :readonly => true %>
          </div>
          
          <br />

          <div class="actions">
            <%= f.submit 'Release Brush holder', :name => 'create' %>
          </div>
      <% end %>
    <% end %>

app/views/brush_holders/_list.html.erb
<div id="filterrific_results" %>
<div><%= page_entries_info brush_holders %></div>

<table class="table table-hover">
  <tr class="active">
    <th class="text-center">Status</th>
    <th class="text-center">Partnumber</th>
    <th class="text-center">Description</th>
    <th class="text-center">Brush holder type</th>
    <th class="text-center">Material</th>
    <th class="text-center">Drawing norm</th>
    <th class="text-center">Corresponding carbon brush</th>
    <th class="text-center">Supplier</th>
    <th class="text-center">Where used product</th>
    <th class="text-center">Where used plant</th>
    <th class="text-center">Reason</th>
  </tr>

<% brush_holders.each do |brush_holder| %>
  <% if brush_holder.release_status == "needs editing" && brush_holder.uploader_name == session[:user_name] %>
    <tr class="danger">
  <% elsif brush_holder.release_status == "pending" && session[:user_role] == "Sectionhead" && brush_holder.uploader_role == "Normal" && brush_holder.uploaded_by_section == session[:user_section] || session[:user_role] == "Departmenthead" && brush_holder.uploader_role == "Sectionhead" && brush_holder.release_status == "pending" %>
    <tr class="warning">
  <% elsif brush_holder.release_status == "pending" || brush_holder.release_status == "needs editing" %>
    <tr class="pending_parts">
  <% else %>
    <tr>
  <% end %>
        <td><%= link_to "#{brush_holder.partnumber}", brush_holder, method: :get %></td>
        <td><%= brush_holder.release_status %></td>
        <td><%= brush_holder.description %></td>
        <td><%= brush_holder.brush_holder_type %></td>
        <td><%= brush_holder.material %></td>
        <td><%= brush_holder.drawing_norm %></td>        
        <td><%= brush_holder.corresponding_carbon_brush %></td>
        <td><%= brush_holder.supplier %></td>
        <td><%= brush_holder.where_used_product %></td>
        <td><%= brush_holder.where_used_plant %></td>        
        <td><%= brush_holder.reason %></td>
    </tr>
<% end %>
</table>
<%= will_paginate brush_holders %>
</div>

app/views/brush_holders/index.html.erb
<h1>Listing brush holders</h1>

<% if flash[:warning] or flash[:notice] %>
  <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
    <%= flash[:warning] || flash[:notice] %>
  </div>

<% end %>

<div class="row">
  <%= form_for_filterrific @filterrific do |f| %>
     <span class="glyphicon glyphicon-search"></span> <%= f.text_field(:search_query, class: 'filterrific-periodically-observed') %>
     <button class="btn btn-default btn-xs" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <span class="glyphicon glyphicon-filter"></span>
  </button>
  <% end %>
</div>

<div class="row">
<div class="collapse" id="collapseExample">
  <%= render(
              partial: 'shared/filter',
              locals: { obj: BrushHolder }) 
  %>
</div>



<%= render(
    partial: 'brush_holders/list', 
    locals: { brush_holders: @brush_holders }) 
%>

<br />

<% if is_section_head? || is_normal? %>
  <%= button_to 'New Brush holder', new_brush_holder_path, :method => :get, class: "btn btn-default" %>
<% elsif is_superadmin? %>
  <%= link_to "Mass Import", new_brush_holder_import_path, class: "btn btn-default" %>
<% end %>

app/views/brush_holders/index.js.erb
<% js = escape_javascript(
  render(partial: 'brush_holders/list', locals: { brush_holders: @brush_holders })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/brush_holders/new.html.erb
<h1>New brush holder</h1>

<%= render 'form' %>

app/views/brush_holders/show.html.erb
<% if flash[:warning] or flash[:notice] %>
  <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
    <%= flash[:warning] || flash[:notice] %>
  </div>

<% end %>

 <%= part_status(@brush_holder) %>
<p>
  <b>Partnumber:</b>
  <%= @brush_holder.partnumber %>
</p>

<p>
  <b>Description:</b>
  <%= @brush_holder.description %>
</p>

<p>
  <b>Brush holder type:</b>
  <%= @brush_holder.brush_holder_type %>
</p>

<p>
  <b>Material:</b>
  <%= @brush_holder.material %>
</p>

<p>
  <b>Drawing norm:</b>
  <%= @brush_holder.drawing_norm %>
</p>

<p>
  <b>Corresponding carbon brush:</b>
  <%= @brush_holder.corresponding_carbon_brush %>
</p>

<p>
  <b>Supplier:</b>
  <%= @brush_holder.supplier %>
</p>

<p>
  <b>Where used product:</b>
  <%= @brush_holder.where_used_product %>
</p>

<p>
  <b>Where used plant:</b>
  <%= @brush_holder.where_used_plant %>
</p><br />

<p>
    <b>Reason for submission:</b>
    <%= @brush_holder.reason %>
  </p><br />

<p>
    <b>Submitted by:</b>
    <%= @brush_holder.uploader_name %>
  </p>

  <p>
    <b>Created at:</b>
    <%= @brush_holder.created_at %>
  </p>

  <p>
    <b>Last updated at:</b>
    <%= @brush_holder.updated_at %>
  </p>

<%= render 'shared/show_actions', :object => @brush_holder %>