config/routes.rb
Rails.application.routes.draw do

    root "admin#index"
  
  resources :users 

  resources :anchor_logos do
    get :reset_filterrific, on: :collection
  end

  resources :ac_motors do
    get :reset_filterrific, on: :collection
  end

  resources :bearings do
    get :reset_filterrific, on: :collection
  end
  resources :greases do
    get :reset_filterrific, on: :collection
  end
  resources :brush_holders do
    get :reset_filterrific, on: :collection
  end
  resources :c_clips do
    get :reset_filterrific, on: :collection
  end
  resources :capacitors do
    get :reset_filterrific, on: :collection
  end
  resources :carbon_brushes do
    get :reset_filterrific, on: :collection
  end
  resources :connectors do
    get :reset_filterrific, on: :collection
  end
  resources :copperwires do
    get :reset_filterrific, on: :collection
  end
  resources :cord_clips do
    get :reset_filterrific, on: :collection
  end
  resources :cords do
    get :reset_filterrific, on: :collection
  end
  resources :grommets do
    get :reset_filterrific, on: :collection
  end
  resources :nuts do
    get :reset_filterrific, on: :collection
  end
  resources :plastic_materials do
    get :reset_filterrific, on: :collection
  end
  resources :screws do
    get :reset_filterrific, on: :collection
  end
  resources :spiral_springs do
    get :reset_filterrific, on: :collection
  end
  resources :springs do
    get :reset_filterrific, on: :collection
  end
  resources :washers do
    get :reset_filterrific, on: :collection
  end

  resources :anchor_logos
  resources :ac_motors
  resources :bearings
  resources :brush_holders
  resources :c_clips
  resources :capacitors
  resources :carbon_brushes
  resources :connectors
  resources :copperwires
  resources :cords
  resources :cord_clips
  resources :greases
  resources :grommets
  resources :nuts
  resources :plastic_materials
  resources :screws
  resources :spiral_springs
  resources :springs
  resources :washers

  resources :anchor_logo_imports
  resources :ac_motor_imports
  resources :bearing_imports
  resources :brush_holder_imports
  resources :c_clip_imports
  resources :capacitor_imports
  resources :carbon_brush_imports
  resources :connector_imports
  resources :copperwire_imports
  resources :cord_imports
  resources :cord_clip_imports
  resources :grease_imports
  resources :grommet_imports
  resources :nut_imports
  resources :plastic_material_imports
  resources :screw_imports
  resources :spiral_spring_imports
  resources :spring_imports
  resources :washer_imports

  resources :ac_motors, :anchor_logos, :bearings, :brush_holders, :c_clips, :capacitors,
            :carbon_brushes, :connectors, :copperwires, :cords, :cord_clips, :greases,
            :grommets, :nuts, :plastic_materials, :screws, :spiral_springs, :springs, :washers do
    member do
      patch :block
      patch :unblock
      patch :approve
      patch :release
      get   :needs_editing
      get   :correct
    end
  end

  
  get "superadmin/approval_by_superadmin"
  get "superadmin/create_by_superadmin"

  get "pending/index"
  get "admin" => "admin#index"

  resources :sessions
  controller :sessions do
    get '/login' => :new, :via => :get
    match '/login' => :create, :via => :post
    delete '/logout', to: 'sessions#destroy', as: :logout
    get 'change_details' => :change_details
    get 'update_details' => :update_details
    get 'show_details' => :show_details
  end

  get "profile/index"
  get "profile/edit"
end

app/models/screw.rb
class Screw < ActiveRecord::Base

   include ValidateMethods
   include CommonConstants

  
  	after_initialize :init

  	

    self.per_page = 15

  	def self.search(query)
  		where('release_status LIKE ? or partnumber LIKE ? or description LIKE ? 
        or screw_drive LIKE ? or screw_head LIKE ? or thread_type LIKE ? 
        or drawing_norm LIKE ? or screw_size LIKE ? or length LIKE ? 
        or connection_material LIKE ? or coating LIKE ? or where_used_product LIKE ? 
        or where_used_plant LIKE ? or remark LIKE ? or reason LIKE ?',
  		"%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", 
      "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", 
      "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", 
      "%#{query}%", "%#{query}%", "%#{query}%")
	end

	def self.to_csv(options = {})
  	CSV.generate(options) do |csv|
  	  csv << column_names
  	  all.each do |screw|
  	  	csv << screw.attributes.values_at(*column_names)
  	  end
  	end
  end

  def self.accessible_attributes
    ["id","partnumber","description","screw_drive","screw_head","thread_type",
    	"screw_size","length","connection_material","coating","drawing_norm",
    	"where_used_product","where_used_plant","remark","reason"]
  end

  def init 
    self.release_status ||= "released"
  end

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :search_query,
      :sorted_by,
      :with_partnumber,
      :with_description,
      :with_screw_drive,
      :with_screw_head,
      :with_thread_type,
      :with_screw_size,
      :with_length,
      :with_connection_material,
      :with_coating,
      :with_drawing_norm,
      :with_where_used_product,
      :with_where_used_plant,
      :with_remark,
      :with_reason
    ]
    )

  def self.options_for_sorted_by
      [
        ['Submission date (newest first)', 'created_at_desc'],
        ['Submission date (oldest first)', 'created_at_asc'],
        ['partnumber (larger number first)','partnumber_at_desc'],
        ['partnumber (smaller number first)','partnumber_at_asc'],
      ]
  end

  def self.partnumbers_for_select
    order('LOWER(partnumber)').map { |e| [e.partnumber, e.partnumber] }.uniq
  end

  def self.descriptions_for_select
    order('LOWER(description)').map { |e| [e.description, e.description] }.uniq
  end

  def self.screw_drives_for_select
    order('LOWER(screw_drive)').map { |e| [e.screw_drive, e.screw_drive] }.uniq
  end

  def self.screw_heads_for_select
    order('LOWER(screw_head)').map { |e| [e.screw_head, e.screw_head] }.uniq
  end

  def self.thread_types_for_select
    order('LOWER(thread_type)').map { |e| [e.thread_type, e.thread_type] }.uniq
  end

  def self.screw_sizes_for_select
    order('LOWER(screw_size)').map { |e| [e.screw_size, e.screw_size] }.uniq
  end

  def self.lengths_for_select
    order('LOWER(length)').map { |e| [e.length, e.length] }.uniq
  end

  def self.connection_materials_for_select
    order('LOWER(connection_material)').map { |e| [e.connection_material, e.connection_material] }.uniq
  end

  def self.coatings_for_select
    order('LOWER(coating)').map { |e| [e.coating, e.coating] }.uniq
  end

  def self.drawing_norms_for_select
    order('LOWER(drawing_norm)').map { |e| [e.drawing_norm, e.drawing_norm] }.uniq
  end

  def self.where_used_products_for_select
    order('LOWER(where_used_product)').map { |e| [e.where_used_product, e.where_used_product] }.uniq
  end

  def self.where_used_plants_for_select
    order('LOWER(where_used_plant)').map { |e| [e.where_used_plant, e.where_used_plant] }.uniq
  end

  def self.remarks_for_select
    order('LOWER(remark)').map { |e| [e.remark, e.remark] }.uniq
  end

  def self.reasons_for_select
    order('LOWER(reason)').map { |e| [e.reason, e.reason] }.uniq
  end
  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
    order("screws.created_at #{ direction }")
    when /^partnumber_/
    order("LOWER(screws.partnumber) #{ direction }")
    when /^description_/
    order("LOWER(screws.description) #{ direction }")
    when /^screw_drive_/
    order("LOWER(screws.screw_drive) #{ direction }")
    when /^screw_head_/
    order("LOWER(screws.screw_head) #{ direction }")
    when /^thread_type_/
    order("LOWER(screws.thread_type) #{ direction }")
    when /^screw_size_/
    order("LOWER(screws.screw_size) #{ direction }")
    when /^length_/
    order("LOWER(screws.length) #{ direction }")
    when /^connection_material_/
    order("LOWER(screws.connection_material) #{ direction }")
    when /^coating_/
    order("LOWER(screws.coating) #{ direction }")
    when /^drawing_norm_/
    order("LOWER(screws.drawing_norm) #{ direction }")
    when /^where_used_product_/
    order("LOWER(screws.where_used_product) #{ direction }")
    when /^where_used_plant_/
    order("LOWER(screws.where_used_plant) #{ direction }")
    when /^remark_/
    order("LOWER(screws.remark) #{ direction }")
    when /^reason_/
    order("LOWER(screws.reason) #{ direction }")
  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end
    
  }
scope :with_partnumber, lambda { |partnumbers| where(partnumber: [*partnumbers])}
scope :with_description, lambda { |descriptions| where(description: [*descriptions])}
scope :with_screw_drive, lambda { |screw_drives| where(screw_drive: [*screw_drives])}
scope :with_screw_head, lambda { |screw_heads| where(screw_head: [*screw_heads])}
scope :with_thread_type, lambda { |thread_types| where(thread_type: [*thread_types])}
scope :with_screw_size, lambda { |screw_sizes| where(screw_size: [*screw_sizes])}
scope :with_length, lambda { |lengths| where(length: [*lengths])}
scope :with_connection_material, lambda { |connection_materials| where(connection_material: [*connection_materials])}
scope :with_coating, lambda { |coatings| where(coating: [*coatings])}
scope :with_drawing_norm, lambda { |drawing_norms| where(drawing_norm: [*drawing_norms])}
scope :with_where_used_product, lambda { |where_used_products| where(where_used_product: [*where_used_products])}
scope :with_where_used_plant, lambda { |where_used_plants| where(where_used_plant: [*where_used_plants])}
scope :with_remark, lambda { |remarks| where(remark: [*remarks])}
scope :with_reason, lambda { |reasons| where(reason: [*reasons])}

scope :search_query, lambda { |query|
  return nil  if query.blank?
  # condition query, parse into individual keywords
  #terms = query.downcase.split(/\s+/)
  if query.is_a? String
    terms = query.downcase
    terms = (terms.gsub('*', '%') + '%').gsub(/%+/, '%')
  else
    terms =  query
  end

  # replace "*" with "%" for wildcard searches,
  # append '%', remove duplicate '%'s
  # terms = terms.map { |e|
  #   (e.gsub('*', '%') + '%').gsub(/%+/, '%')
  # }
  # configure number of OR conditions for provision
  # of interpolation arguments. Adjust this if you
  # change the number of OR conditions.
  # num_or_conds = 16
  where("LOWER(screws.partnumber) LIKE ? OR LOWER(screws.description) LIKE ? OR LOWER(screws.screw_drive) LIKE ?
         OR LOWER(screws.screw_head) LIKE ? OR LOWER(screws.thread_type) LIKE ? OR LOWER(screws.screw_size) LIKE ?
          OR LOWER(screws.length) LIKE ? OR LOWER(screws.connection_material) LIKE ? OR LOWER(screws.coating) LIKE ?
           OR LOWER(screws.drawing_norm) LIKE ? OR LOWER(screws.where_used_product) LIKE ? OR LOWER(screws.where_used_plant) LIKE ?
            OR LOWER(screws.remark) LIKE ? OR LOWER(screws.reason) LIKE ?",
             terms, terms, terms, terms, terms, terms, terms, terms, 
             terms, terms, terms, terms, terms, terms)
}

end

app/controllers/screws_controller.rb
class ScrewsController < ApplicationController
  before_action :set_screw, only: [:show, :edit, :update, :destroy]

  # GET /screws
  def index
    @filterrific = initialize_filterrific(
      Screw, 
      params[:filterrific],
      select_options: {
      sorted_by: Screw.options_for_sorted_by,
      with_partnumber: Screw.partnumbers_for_select,
      with_description: Screw.descriptions_for_select,
      with_screw_drive: Screw.screw_drives_for_select,
      with_screw_head: Screw.screw_heads_for_select,
      with_thread_type: Screw.thread_types_for_select,
      with_screw_size: Screw.screw_sizes_for_select,
      with_length: Screw.lengths_for_select,
      with_connection_material: Screw.connection_materials_for_select,
      with_coating: Screw.coatings_for_select,
      with_drawing_norm: Screw.drawing_norms_for_select,
      with_where_used_product: Screw.where_used_products_for_select,
      with_where_used_plant: Screw.where_used_plants_for_select,
      with_remark: Screw.remarks_for_select,
      with_reason: Screw.reasons_for_select
    }) or return
    @screws = @filterrific.find.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  rescue_from ActiveRecord::RecordNotFound, with: :reset_filterrific

  # GET /screws/1
  def show
  end

  # GET /screws/new
  def new
    @screw = Screw.new
  end

  # GET /screws/1/edit
  def edit
    @object = Screw.find(params[:id])
    render 'shared/edit'
  end

  def correct
    @object = Screw.find(params[:id])
    render 'shared/correct'
  end

  # POST /screws
  def create
    @screw = Screw.new(screw_params)

    @screw.uploaded_by_section = session[:user_section]
    @screw.uploader_role = session[:user_role]
    @screw.uploader_name = session[:user_name]
    @screw.release_status = "pending"

    if @screw.save
      redirect_to @screw, notice: 'Screw was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /screws/1

 def update
    @screw = Screw.find(params[:id])
    if params[:to_needs_editing] # if update call from needs editing, set part status accordingly
      @screw.release_status = "needs editing"
    else
      @screw.release_status = "pending"
    end
    if @screw.update(screw_params)
      redirect_to @screw, notice: 'Screw was successfully updated.'
    else
      render :edit
    end
  end

 def approve
    @screw = Screw.find(params[:id])
    @screw.release_status = "approved draft"
    @screw.save
    respond_to do |format|
      format.html { redirect_to(screws_url) }
      format.xml  { head :ok }
    end
  end

  def release
    @screw = Screw.find(params[:id])
    @screw.release_status = "released"
    @screw.save
    respond_to do |format|
      format.html { redirect_to(screws_url) }
      format.xml  { head :ok }
    end
  end

 def block
    @screw = Screw.find(params[:id])
    @screw.release_status = "block"
    @screw.save
    respond_to do |format|
      format.html { redirect_to(screws_url) }
      format.xml  { head :ok }
    end
  end

  def unblock
    @screw = Screw.find(params[:id])
    @screw.release_status = "released"
    @screw.save
    respond_to do |format|
      format.html { redirect_to(screws_url) }
      format.xml  { head :ok }
    end
  end

  def needs_editing
    @object = Screw.find(params[:id])
    render 'shared/needs_editing'
  end

  # DELETE /screws/1
  def destroy
    @screw.destroy
    redirect_to screws_url, notice: 'Screw was successfully destroyed.'
  end

  def reset_filterrific
      # Clear session persistence
      session[:filterrific_screws] = nil
      # Redirect back to the index action for default filter settings.
      redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screw
      @screw = Screw.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def screw_params
      params.require(:screw).permit(:id, :partnumber, :description, :screw_drive, :screw_head, 
        :thread_type, :screw_size, :length, :connection_material, :coating, :drawing_norm, 
        :where_used_product, :where_used_plant, :remark, :release_status,
        :need_to_edit_partnumber, :need_to_edit_description, :need_to_edit_screw_drive, 
        :need_to_edit_screw_head, :need_to_edit_thread_type, :need_to_edit_screw_size, 
        :need_to_edit_length, :need_to_edit_connection_material, :need_to_edit_coating, 
        :need_to_edit_drawing_norm, :need_to_edit_where_used_product, :need_to_edit_where_used_plant, 
        :need_to_edit_remark,:need_to_edit_reason,
        :reason)
    end
end

app/helpers/screws_helper.rb
module ScrewsHelper
end

app/views/screws/_form.html.erb
<%= form_for(@screw) do |f| %>
  <% if @screw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screw.errors.count, "error") %> prohibited this screw from being saved:</h2>

      <ul>
      <% @screw.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :partnumber %><br>
    <%= f.text_field :partnumber %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :screw_drive %><br>
    <%= f.text_field :screw_drive %>
  </div>
  <div class="field">
    <%= f.label :screw_head %><br>
    <%= f.text_field :screw_head %>
  </div>
  <div class="field">
    <%= f.label :thread_type %><br>
    <%= f.text_field :thread_type %>
  </div>
  <div class="field">
    <%= f.label :screw_size %><br>
    <%= f.text_field :screw_size %>
  </div>
  <div class="field">
    <%= f.label :length %><b> (You need to use a dot, for example: 0.53)</b><br>
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :connection_material %><br>
    <%= f.text_field :connection_material %>
  </div>
  <div class="field">
    <%= f.label :coating %><br>
    <%= f.text_field :coating %>
  </div>
  <div class="field">
    <%= f.label :drawing_norm %><br>
    <%= f.text_field :drawing_norm %>
  </div>
  <div class="field">
    <%= f.label :where_used_product %><br>
    <%= f.text_field :where_used_product %>
  </div>
  <div class="field">
    <%= f.label :where_used_plant %><br>
    <%= f.text_field :where_used_plant %>
  </div>
  <div class="field">
    <%= f.label :remark %><br>
    <%= f.text_field :remark %>
  </div>
  <br />
  <div class="field">
    <%= f.label :reason_for_submission? %><br />
    <%= f.text_field :reason %>
  </div>   
  <br />

  <% if session[:user_role] == "Normal" && @screw.uploader_name == nil || session[:user_role] == "Sectionhead" && @screw.uploader_name == nil %>
      <div class="field">
        <%= f.label :release_status %><br />
        <%= f.text_field :release_status, :value => "pending", :readonly => true %>
      </div>
  <% end %>
    
  <% if @screw.uploader_name != session[:user_name] && session[:user_role] != "Superadmin" %>
    <div class="actions">
      <%= f.submit 'Submit Screw', :name => 'submit' %>
    </div>
  <% end %>

  <% if @screw.uploader_name == session[:user_name] || session[:user_role] == "Superadmin" %>
    <div class="actions">
      <%= f.submit 'Update Screw', :name => 'create' %>
    </div>
  <% end %>
<% end %>

app/views/screws/_form_finalrelease.html.erb
<br />
<h2>This part is waiting to get released!</h2>
<br />

<p>
  <strong>Partnumber:</strong>
  <%= @screw.partnumber %>
</p>

<p>
  <strong>Description:</strong>
  <%= @screw.description %>
</p>

<p>
  <strong>Screw drive:</strong>
  <%= @screw.screw_drive %>
</p>

<p>
  <strong>Screw head:</strong>
  <%= @screw.screw_head %>
</p>

<p>
  <strong>Thread type:</strong>
  <%= @screw.thread_type %>
</p>

<p>
  <strong>Screw size:</strong>
  <%= @screw.screw_size %>
</p>

<p>
  <strong>Length:</strong>
  <%= @screw.length %>
</p>

<p>
  <strong>Connection material:</strong>
  <%= @screw.connection_material %>
</p>

<p>
  <strong>Coating:</strong>
  <%= @screw.coating %>
</p>

<p>
  <strong>Drawing norm:</strong>
  <%= @screw.drawing_norm %>
</p>

<p>
  <strong>Where used product:</strong>
  <%= @screw.where_used_product %>
</p>

<p>
  <strong>Where used plant:</strong>
  <%= @screw.where_used_plant %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @screw.remark %>
</p>

<br />

<p>
    <b>Reason for submission:</b>
    <%= @screw.reason %>
  </p><br />

  <% if session[:user_role] == "Sectionhead" && @screw.uploader_role == "Normal" && @screw.release_status == "approved draft" && @screw.uploaded_by_section == session[:user_section] %> 

    <%= form_for(@screw) do |f| %>
        <% if @screw.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@screw.errors.count, "error") %> prohibited this screw from being saved:</h2>

            <ul>
            <% @screw.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <div class="field">
              <%= f.label :Status? %><br />
              <%= f.text_field :release_status, :value => "released", :readonly => true %>
          </div>
          
          <br />

          <div class="actions">
            <%= f.submit 'Release Screw', :name => 'create' %>
          </div>
      <% end %>
    <% end %>

app/views/screws/_list.html.erb
<div id="filterrific_results" %>
<div><%= page_entries_info screws %></div>

<table class="table table-hover">
  <tr class="active">
      <th class="text-center">Partnumber</th>
      <th class="text-center">Status</th>
      <th class="text-center">Description</th>
      <th class="text-center">Screw drive</th>
      <th class="text-center">Screw head</th>
      <th class="text-center">Thread type</th>
      <th class="text-center">Screw size</th>
      <th class="text-center">Length</th>
      <th class="text-center">Connection material</th>
      <th class="text-center">Coating</th>
      <th class="text-center">Drawing norm</th>
      <th class="text-center">Where used product</th>
      <th class="text-center">Where used plant</th>
      <th class="text-center">Remark</th>
      <th class="text-center">Reason</th>
    </tr>

  <tbody>
    <% screws.each do |screw| %>
      <% if screw.release_status == "needs editing" && screw.uploader_name == session[:user_name] %>
        <tr class="danger">
      <% elsif screw.release_status == "pending" && session[:user_role] == "Sectionhead" && screw.uploader_role == "Normal" && screw.uploaded_by_section == session[:user_section] || session[:user_role] == "Departmenthead" && screw.uploader_role == "Sectionhead" && screw.release_status == "pending" %>
        <tr class="warning">
      <% elsif screw.release_status == "pending" || screw.release_status == "needs editing" %>
        <tr class="pending_parts">
      <% else %>
        <tr>
      <% end %>
        <td><%= link_to "#{screw.partnumber}", screw, method: :get %></td>
        <td><%= screw.release_status %></td>
        <td><%= screw.description %></td>
        <td><%= screw.screw_drive %></td>
        <td><%= screw.screw_head %></td>
        <td><%= screw.thread_type %></td>
        <td><%= screw.screw_size %></td>
        <td><%= screw.length %></td>
        <td><%= screw.connection_material %></td>
        <td><%= screw.coating %></td>
        <td><%= screw.drawing_norm %></td>
        <td><%= screw.where_used_product %></td>
        <td><%= screw.where_used_plant %></td>
        <td><%= screw.remark %></td>
        <td><%= screw.reason %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate screws %>
</div>

app/views/screws/index.html.erb
<h1>Listing screws</h1>

<% if flash[:warning] or flash[:notice] %>
  <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
    <%= flash[:warning] || flash[:notice] %>
  </div>

<% end %>
<div class="row">
  <%= form_for_filterrific @filterrific do |f| %>
     <span class="glyphicon glyphicon-search"></span> <%= f.text_field(:search_query, class: 'filterrific-periodically-observed') %>
     <button class="btn btn-default btn-xs" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <span class="glyphicon glyphicon-filter"></span>
  </button>
  <% end %>
</div>

<div class="row">
<div class="collapse" id="collapseExample">
  <%= render(
              partial: 'shared/filter',
              locals: { obj: Screw }) 
  %>
</div>

<%= render(
    partial: 'screws/list', 
    locals: { screws: @screws }) 
%>

<br />

<% if is_section_head? || is_normal? %>
  <%= button_to 'New Screw', new_screw_path, :method => :get, class: "btn btn-default" %>
<% elsif is_superadmin? %>
  <%= link_to "Mass Import", new_screw_import_path, class: "btn btn-default" %>
<% end %>

app/views/screws/index.js.erb
<% js = escape_javascript(
  render(partial: 'screws/list', locals: { screws: @screws })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/screws/new.html.erb
<h1>New screw</h1>

<%= render 'form' %>

app/views/screws/show.html.erb
<% if flash[:warning] or flash[:notice] %>
  <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
    <%= flash[:warning] || flash[:notice] %>
  </div>

<% end %>

 <%= part_status(@screw) %>

<p>
  <strong>Partnumber:</strong>
  <%= @screw.partnumber %>
</p>

<p>
  <strong>Description:</strong>
  <%= @screw.description %>
</p>

<p>
  <strong>Screw drive:</strong>
  <%= @screw.screw_drive %>
</p>

<p>
  <strong>Screw head:</strong>
  <%= @screw.screw_head %>
</p>

<p>
  <strong>Thread type:</strong>
  <%= @screw.thread_type %>
</p>

<p>
  <strong>Screw size:</strong>
  <%= @screw.screw_size %>
</p>

<p>
  <strong>Length:</strong>
  <%= @screw.length %>
</p>

<p>
  <strong>Connection material:</strong>
  <%= @screw.connection_material %>
</p>

<p>
  <strong>Coating:</strong>
  <%= @screw.coating %>
</p>

<p>
  <strong>Drawing norm:</strong>
  <%= @screw.drawing_norm %>
</p>

<p>
  <strong>Where used product:</strong>
  <%= @screw.where_used_product %>
</p>

<p>
  <strong>Where used plant:</strong>
  <%= @screw.where_used_plant %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @screw.remark %>
</p>

<br />

<p>
    <b>Reason for submission:</b>
    <%= @screw.reason %>
  </p><br />

  <p>
    <b>Submitted by:</b>
    <%= @screw.uploader_name %>
  </p>

  <p>
    <b>Created at:</b>
    <%= @screw.created_at %>
  </p>

  <p>
    <b>Last updated at:</b>
    <%= @screw.updated_at %>
  </p>

<%= render 'shared/show_actions', :object => @screw %>