config/routes.rb
Rails.application.routes.draw do

    root "admin#index"
  
  resources :users 

  resources :anchor_logos do
    get :reset_filterrific, on: :collection
  end

  resources :ac_motors do
    get :reset_filterrific, on: :collection
  end

  resources :bearings do
    get :reset_filterrific, on: :collection
  end
  resources :greases do
    get :reset_filterrific, on: :collection
  end
  resources :brush_holders do
    get :reset_filterrific, on: :collection
  end
  resources :c_clips do
    get :reset_filterrific, on: :collection
  end
  resources :capacitors do
    get :reset_filterrific, on: :collection
  end
  resources :carbon_brushes do
    get :reset_filterrific, on: :collection
  end
  resources :connectors do
    get :reset_filterrific, on: :collection
  end
  resources :copperwires do
    get :reset_filterrific, on: :collection
  end
  resources :cord_clips do
    get :reset_filterrific, on: :collection
  end
  resources :cords do
    get :reset_filterrific, on: :collection
  end
  resources :grommets do
    get :reset_filterrific, on: :collection
  end
  resources :nuts do
    get :reset_filterrific, on: :collection
  end
  resources :plastic_materials do
    get :reset_filterrific, on: :collection
  end
  resources :screws do
    get :reset_filterrific, on: :collection
  end
  resources :spiral_springs do
    get :reset_filterrific, on: :collection
  end
  resources :springs do
    get :reset_filterrific, on: :collection
  end
  resources :washers do
    get :reset_filterrific, on: :collection
  end

  resources :anchor_logos
  resources :ac_motors
  resources :bearings
  resources :brush_holders
  resources :c_clips
  resources :capacitors
  resources :carbon_brushes
  resources :connectors
  resources :copperwires
  resources :cords
  resources :cord_clips
  resources :greases
  resources :grommets
  resources :nuts
  resources :plastic_materials
  resources :screws
  resources :spiral_springs
  resources :springs
  resources :washers

  resources :anchor_logo_imports
  resources :ac_motor_imports
  resources :bearing_imports
  resources :brush_holder_imports
  resources :c_clip_imports
  resources :capacitor_imports
  resources :carbon_brush_imports
  resources :connector_imports
  resources :copperwire_imports
  resources :cord_imports
  resources :cord_clip_imports
  resources :grease_imports
  resources :grommet_imports
  resources :nut_imports
  resources :plastic_material_imports
  resources :screw_imports
  resources :spiral_spring_imports
  resources :spring_imports
  resources :washer_imports

  resources :ac_motors, :anchor_logos, :bearings, :brush_holders, :c_clips, :capacitors,
            :carbon_brushes, :connectors, :copperwires, :cords, :cord_clips, :greases,
            :grommets, :nuts, :plastic_materials, :screws, :spiral_springs, :springs, :washers do
    member do
      patch :block
      patch :unblock
      patch :approve
      patch :release
      get   :needs_editing
      get   :correct
    end
  end

  
  get "superadmin/approval_by_superadmin"
  get "superadmin/create_by_superadmin"

  get "pending/index"
  get "admin" => "admin#index"

  resources :sessions
  controller :sessions do
    get '/login' => :new, :via => :get
    match '/login' => :create, :via => :post
    delete '/logout', to: 'sessions#destroy', as: :logout
    get 'change_details' => :change_details
    get 'update_details' => :update_details
    get 'show_details' => :show_details
  end

  get "profile/index"
  get "profile/edit"
end

app/models/copperwire.rb
class Copperwire < ActiveRecord::Base

   include ValidateMethods
   include CommonConstants

  	after_initialize :init

  	SELF_BONDED = [nil, "No", "Yes"]
  	

    self.per_page = 15

  	def self.search(query)
  		where(
        'release_status LIKE ? or 
        partnumber LIKE ? or 
        description LIKE ? or 
        copperwire_type LIKE ? or 
        self_bonded LIKE ? or 
        diameter LIKE ? or 
        drawing_norm LIKE ? or 
        supplier LIKE ? or 
        where_used_product LIKE ? or 
        where_used_plant LIKE ? or 
        reason LIKE ?',
  		"%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%" , "%#{query}%", 
      "%#{query}%" , "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")
	end

	def self.to_csv(options = {})
  	CSV.generate(options) do |csv|
  	  csv << column_names
  	  all.each do |copperwire|
  	  	csv << copperwire.attributes.values_at(*column_names)
  	  end
  	end
  end

  def self.accessible_attributes
    ["id","partnumber","description","copperwire_type","self_bonded",
    	"diameter","drawing_norm","supplier","where_used_product","where_used_plant","reason"]
  end

  def init 
    self.release_status ||= "released"
  end

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :search_query,
      :sorted_by,
      :with_partnumber,
      :with_description,
      :with_copperwire_type,
      :with_self_bonded,
      :with_diameter,
      :with_drawing_norm,
      :with_supplier,
      :with_where_used_product,
      :with_where_used_plant,
      :with_reason
    ]
    )

  def self.options_for_sorted_by
      [
        ['Submission date (newest first)', 'created_at_desc'],
        ['Submission date (oldest first)', 'created_at_asc'],
        ['partnumber (larger number first)','partnumber_at_desc'],
        ['partnumber (smaller number first)','partnumber_at_asc'],
      ]
  end

  def self.partnumbers_for_select
    order('LOWER(partnumber)').map { |e| [e.partnumber, e.partnumber] }.uniq
  end

  def self.descriptions_for_select
    order('LOWER(description)').map { |e| [e.description, e.description] }.uniq
  end

  def self.copperwire_types_for_select
    order('LOWER(copperwire_type)').map { |e| [e.copperwire_type, e.copperwire_type] }.uniq
  end

  def self.self_bondeds_for_select
    order('LOWER(self_bonded)').map { |e| [e.self_bonded, e.self_bonded] }.uniq
  end

  def self.diameters_for_select
    order('LOWER(diameter)').map { |e| [e.diameter, e.diameter] }.uniq
  end

  def self.drawing_norms_for_select
    order('LOWER(drawing_norm)').map { |e| [e.drawing_norm, e.drawing_norm] }.uniq
  end

  def self.suppliers_for_select
    order('LOWER(supplier)').map { |e| [e.supplier, e.supplier] }.uniq
  end

  def self.where_used_products_for_select
    order('LOWER(where_used_product)').map { |e| [e.where_used_product, e.where_used_product] }.uniq
  end

  def self.where_used_plants_for_select
    order('LOWER(where_used_plant)').map { |e| [e.where_used_plant, e.where_used_plant] }.uniq
  end
  def self.reasons_for_select
    order('LOWER(reason)').map { |e| [e.reason, e.reason] }.uniq
  end

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
    order("copperwires.created_at #{ direction }")
    when /^partnumber_/
    order("LOWER(copperwires.partnumber) #{ direction }")
    when /^description_/
    order("LOWER(copperwires.description) #{ direction }")
    when /^copperwire_type_/
    order("LOWER(copperwires.copperwire_type) #{ direction }")
    when /^self_bonded_/
    order("LOWER(copperwires.self_bonded) #{ direction }")
    when /^diameter_/
    order("LOWER(copperwires.diameter) #{ direction }")
    when /^drawing_norm_/
    order("LOWER(copperwires.drawing_norm) #{ direction }")
    when /^supplier_/
    order("LOWER(copperwires.supplier) #{ direction }")
    when /^where_used_product_/
    order("LOWER(copperwires.where_used_product) #{ direction }")
    when /^where_used_plant_/
    order("LOWER(copperwires.where_used_plant) #{ direction }")
    when /^reason_/
    order("LOWER(copperwires.reason) #{ direction }")
  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end
    
  }
scope :with_partnumber, lambda { |partnumbers| where(partnumber: [*partnumbers])}
scope :with_description, lambda { |descriptions| where(description: [*descriptions])}
scope :with_copperwire_type, lambda { |copperwire_types| where(copperwire_type: [*copperwire_types])}
scope :with_self_bonded, lambda { |self_bondeds| where(self_bonded: [*self_bondeds])}
scope :with_diameter, lambda { |diameters| where(diameter: [*diameters])}
scope :with_drawing_norm, lambda { |drawing_norms| where(drawing_norm: [*drawing_norms])}
scope :with_supplier, lambda { |suppliers| where(supplier: [*suppliers])}
scope :with_reason, lambda { |reasons| where(reason: [*reasons])}
scope :with_where_used_product, lambda { |where_used_products| where(where_used_product: [*where_used_products])}
scope :with_where_used_plant, lambda { |where_used_plants| where(where_used_plant: [*where_used_plants])}

scope :search_query, lambda { |query|
  return nil  if query.blank?
  # condition query, parse into individual keywords
  #terms = query.downcase.split(/\s+/)
  if query.is_a? String
    terms = query.downcase
    terms = (terms.gsub('*', '%') + '%').gsub(/%+/, '%')
  else
    terms =  query
  end

  # replace "*" with "%" for wildcard searches,
  # append '%', remove duplicate '%'s
  # terms = terms.map { |e|
  #   (e.gsub('*', '%') + '%').gsub(/%+/, '%')
  # }
  # configure number of OR conditions for provision
  # of interpolation arguments. Adjust this if you
  # change the number of OR conditions.
  # num_or_conds = 7
  where("LOWER(copperwires.partnumber) LIKE ? OR 
          LOWER(copperwires.description) LIKE ? OR 
          LOWER(copperwires.copperwire_type) LIKE ? OR 
          LOWER(copperwires.self_bonded) LIKE ? OR 
          LOWER(copperwires.diameter) LIKE ? OR 
          LOWER(copperwires.drawing_norm) LIKE ? OR 
          LOWER(copperwires.supplier) LIKE ? OR 
          LOWER(copperwires.where_used_product) LIKE ? OR 
          LOWER(copperwires.where_used_plant) LIKE ? OR 
          LOWER(copperwires.reason) LIKE ?",
          terms, terms, terms, terms, terms, 
          terms, terms, terms, terms, terms)
}
end

app/controllers/copperwires_controller.rb
class CopperwiresController < ApplicationController
  # GET /copperwires
  # GET /copperwires.xml
  def index
    @filterrific = initialize_filterrific(
      Copperwire, 
      params[:filterrific],
      select_options: {
      sorted_by: Copperwire.options_for_sorted_by,
      with_partnumber: Copperwire.partnumbers_for_select,
      with_description: Copperwire.descriptions_for_select,
      with_copperwire_type: Copperwire.copperwire_types_for_select,
      with_self_bonded: Copperwire.self_bondeds_for_select,
      with_diameter: Copperwire.diameters_for_select,
      with_drawing_norm: Copperwire.drawing_norms_for_select,
      with_supplier: Copperwire.suppliers_for_select,
      with_where_used_product: Copperwire.where_used_products_for_select,
      with_where_used_plant: Copperwire.where_used_plants_for_select,
      with_reason: Copperwire.reasons_for_select,
    }) or return
    @copperwires = @filterrific.find.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  rescue_from ActiveRecord::RecordNotFound, with: :reset_filterrific

  # GET /copperwires/1
  # GET /copperwires/1.xml
  def show
    @copperwire = Copperwire.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @copperwire }
    end
  end

  # GET /copperwires/new
  # GET /copperwires/new.xml
  def new
    @copperwire = Copperwire.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @copperwire }
    end
  end

  # GET /copperwires/1/edit
  def edit
    @copperwire = Copperwire.find(params[:id])
    @object = Copperwire.find(params[:id])
    render 'shared/edit'
  end

  def correct
    @object = Copperwire.find(params[:id])
    render 'shared/correct'
  end

  # POST /copperwires
  # POST /copperwires.xml
  def create
    @copperwire = Copperwire.new(copperwire_params)

    @copperwire.uploaded_by_section = session[:user_section]
    @copperwire.uploader_role = session[:user_role]
    @copperwire.uploader_name = session[:user_name]
    @copperwire.release_status = "pending"

    respond_to do |format|
      if @copperwire.save
        format.html { redirect_to(@copperwire, :notice => 'Copperwire was successfully created.') }
        format.xml  { render :xml => @copperwire, :status => :created, :location => @copperwire }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @copperwire.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /copperwires/1
  # PUT /copperwires/1.xml
  def update
    @copperwire = Copperwire.find(params[:id])
    if params[:to_needs_editing] # if update call from needs editing, set part status accordingly
      @copperwire.release_status = "needs editing"
    else
      @copperwire.release_status = "pending"
    end
    respond_to do |format|
      if @copperwire.update_attributes(copperwire_params)
        format.html { redirect_to(@copperwire, :notice => 'Copperwire was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @copperwire.errors, :status => :unprocessable_entity }
      end
    end
  end

  def approve
    @copperwire = Copperwire.find(params[:id])
    @copperwire.release_status = "approved draft"
    @copperwire.save
    respond_to do |format|
      format.html { redirect_to(copperwires_url) }
      format.xml  { head :ok }
    end
  end

  def release
    @copperwire = Copperwire.find(params[:id])
    @copperwire.release_status = "released"
    @copperwire.save
    respond_to do |format|
      format.html { redirect_to(copperwires_url) }
      format.xml  { head :ok }
    end
  end

   def block
    @copperwire = Copperwire.find(params[:id])
    @copperwire.release_status = "block"
    @copperwire.save
    respond_to do |format|
      format.html { redirect_to(copperwires_url) }
      format.xml  { head :ok }
    end
  end

  def unblock
    @copperwire = Copperwire.find(params[:id])
    @copperwire.release_status = "released"
    @copperwire.save
    respond_to do |format|
      format.html { redirect_to(copperwires_url) }
      format.xml  { head :ok }
    end
  end

  def needs_editing
    @object = Copperwire.find(params[:id])
    render 'shared/needs_editing'
  end

  # DELETE /copperwires/1
  # DELETE /copperwires/1.xml
  def destroy
    @copperwire = Copperwire.find(params[:id])
    @copperwire.destroy

    respond_to do |format|
      format.html { redirect_to(copperwires_url) }
      format.xml  { head :ok }
    end
  end

  def reset_filterrific
    # Clear session persistence
    session[:filterrific_copperwires] = nil
    # Redirect back to the index action for default filter settings.
    redirect_to action: :index
  end
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_copperwire
      @copperwire = Copperwire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def copperwire_params
      params.require(:copperwire).permit(
        :id, :partnumber, :description, :copperwire_type, :self_bonded, 
        :diameter, :drawing_norm, :supplier, :where_used_product, :where_used_plant, :release_status,
        :need_to_edit_partnumber, :need_to_edit_description, :need_to_edit_copperwire_type, 
        :need_to_edit_self_bonded, :need_to_edit_diameter, :need_to_edit_drawing_norm, 
        :need_to_edit_supplier, :need_to_edit_where_used_product,:need_to_edit_where_used_plant,
        :reason,:need_to_edit_reason,)
    end

app/helpers/copperwires_helper.rb
module CopperwiresHelper
end

app/views/copperwires/_form.html.erb
<%= form_for(@copperwire) do |f| %>
  <% if @copperwire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@copperwire.errors.count, "error") %> prohibited this copperwire from being saved:</h2>

      <ul>
      <% @copperwire.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :partnumber %><br />
    <%= f.text_field :partnumber %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label :copperwire_type %><br />
    <%= f.text_field :copperwire_type %>
  </div>

  <div class="field">
    <%= f.label :self_bonded %><br />
    <%= f.select :self_bonded, Copperwire::SELF_BONDED %>
  </div>

  <div class="field">
    <%= f.label :diameter %><b> (You need to use a dot, for example: 0.53)</b><br />
    <%= f.text_field :diameter %>
  </div>
  <div class="field">
    <%= f.label :drawing_norm %><br />
    <%= f.text_field :drawing_norm %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br />
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :where_used_product %><br />
    <%= f.text_field :where_used_product %>
  </div>
  <div class="field">
    <%= f.label :where_used_plant %><br />
    <%= f.text_field :where_used_plant %>
  </div>
  <br />
  <div class="field">
    <%= f.label :reason_for_submission? %><br />
    <%= f.text_field :reason %>
  </div>   
  <br />
  
  <% if session[:user_role] == "Normal" && @copperwire.uploader_name == nil || session[:user_role] == "Sectionhead" && @copperwire.uploader_name == nil %>
      <div class="field">
        <%= f.label :release_status %><br />
        <%= f.text_field :release_status, :value => "pending", :readonly => true %>
      </div>
  <% end %>
    
  <% if @copperwire.uploader_name != session[:user_name] && session[:user_role] != "Superadmin" %>
    <div class="actions">
      <%= f.submit 'Submit Copperwire', :name => 'submit' %>
    </div>
  <% end %>

  <% if @copperwire.uploader_name == session[:user_name] || session[:user_role] == "Superadmin" %>
    <div class="actions">
      <%= f.submit 'Update Copperwire', :name => 'create' %>
    </div>
  <% end %>
<% end %>

app/views/copperwires/_form_finalrelease.html.erb
<br />
<h2>This part is waiting to get released!</h2>
<br />
  <p>
    <b>Partnumber:</b>
    <%= @copperwire.partnumber %>
  </p>

  <p>
    <b>Description:</b>
    <%= @copperwire.description %>
  </p>

  <p>
    <b>Copperwire type:</b>
    <%= @copperwire.copperwire_type %>
  </p>

  <p>
    <b>Self bonded:</b>
    <%= @copperwire.self_bonded %>
  </p>

  <p>
    <b>Diameter:</b>
    <%= @copperwire.diameter %>
  </p>

  <p>
    <b>Drawing norm:</b>
    <%= @copperwire.drawing_norm %>
  </p>

  <p>
    <b>Supplier:</b>
    <%= @copperwire.supplier %>
  </p>

  <p>
    <b>Where used product:</b>
    <%= @copperwire.where_used_product %>
  </p>

  <p>
    <b>Where used plant:</b>
    <%= @copperwire.where_used_plant %>
  </p>
  <br />

  <p>
    <b>Reason for submission:</b>
    <%= @copperwire.reason %>
  </p><br />

  <% if session[:user_role] == "Sectionhead" && @copperwire.uploader_role == "Normal" && @copperwire.release_status == "approved draft" && @copperwire.uploaded_by_section == session[:user_section] %> 

    <%= form_for(@copperwire) do |f| %>
        <% if @copperwire.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@copperwire.errors.count, "error") %> prohibited this copperwire from being saved:</h2>

            <ul>
            <% @copperwire.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <div class="field">
              <%= f.label :Status? %><br />
              <%= f.text_field :release_status, :value => "released", :readonly => true %>
          </div>
          
          <br />

          <div class="actions">
            <%= f.submit 'Release Copperwire', :name => 'create' %>
          </div>
      <% end %>
    <% end %>

app/views/copperwires/_list.html.erb
<div id="filterrific_results" %>
<div><%= page_entries_info copperwires %></div>

<table class="table table-hover">
  <tr class="active">
    <th class="text-center">Partnumber</th>
    <th class="text-center">Status</th>
    <th class="text-center">Description</th>
    <th class="text-center">Copperwire type</th>
    <th class="text-center">Self bonded</th>
    <th class="text-center">Diameter</th>
    <th class="text-center">Drawing norm</th>
    <th class="text-center">Supplier</th>
    <th class="text-center">Where used product</th>
    <th class="text-center">Where used plant</th>
    <th class="text-center">Reason</th>

    
  </tr>

<% copperwires.each do |copperwire| %>
  <% if copperwire.release_status == "needs editing" && copperwire.uploader_name == session[:user_name] %>
    <tr class="danger">
  <% elsif copperwire.release_status == "pending" && session[:user_role] == "Sectionhead" && copperwire.uploader_role == "Normal" && copperwire.uploaded_by_section == session[:user_section] || session[:user_role] == "Departmenthead" && copperwire.uploader_role == "Sectionhead" && copperwire.release_status == "pending" %>
    <tr class="warning">
  <% elsif copperwire.release_status == "pending" || copperwire.release_status == "needs editing" %>
    <tr class="pending_parts">
  <% else %>
    <tr>
  <% end %>
        <td><%= link_to "#{copperwire.partnumber}", copperwire, method: :get %></td>
        <td><%= copperwire.release_status %></td>
        <td><%= copperwire.description %></td>
        <td><%= copperwire.copperwire_type %></td>
        <td><%= copperwire.self_bonded %></td>
        <td><%= copperwire.diameter %></td>
        <td><%= copperwire.drawing_norm %></td>
        <td><%= copperwire.supplier %></td>
        <td><%= copperwire.where_used_product %></td>
        <td><%= copperwire.where_used_plant %></td>
        <td><%= copperwire.reason %></td>
    </tr>
<% end %>
</table>
<%= will_paginate copperwires %>
</div>

app/views/copperwires/index.html.erb
<h1>Listing copperwires</h1>

<% if flash[:warning] or flash[:notice] %>
  <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
    <%= flash[:warning] || flash[:notice] %>
  </div>

<% end %>
<div class="row">
  <%= form_for_filterrific @filterrific do |f| %>
     <span class="glyphicon glyphicon-search"></span> <%= f.text_field(:search_query, class: 'filterrific-periodically-observed') %>
     <button class="btn btn-default btn-xs" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <span class="glyphicon glyphicon-filter"></span>
  </button>
  <% end %>
</div>

<div class="row">
<div class="collapse" id="collapseExample">
  <%= render(
              partial: 'shared/filter',
              locals: { obj: Copperwire }) 
  %>
</div>

<%= render(
    partial: 'copperwires/list', 
    locals: { copperwires: @copperwires }) 
%>

<br />

<% if is_section_head? || is_normal? %>
  <%= button_to 'New Copperwire', new_copperwire_path, :method => :get, class: "btn btn-default" %>
<% elsif is_superadmin? %>
  <%= link_to "Mass Import", new_copperwire_import_path, class: "btn btn-default" %>
<% end %>

app/views/copperwires/index.js.erb
<% js = escape_javascript(
  render(partial: 'copperwires/list', locals: { copperwires: @copperwires })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/copperwires/new.html.erb
<h1>New copperwire</h1>

<%= render 'form' %>

app/views/copperwires/show.html.erb
<% if flash[:warning] or flash[:notice] %>
  <div id="notice" <% if flash[:warning] %>class="warning"<% end %>>
    <%= flash[:warning] || flash[:notice] %>
  </div>

<% end %>
 <%= part_status(@copperwire) %>
  <p>
    <b>Partnumber:</b>
    <%= @copperwire.partnumber %>
  </p>

  <p>
    <b>Description:</b>
    <%= @copperwire.description %>
  </p>

  <p>
    <b>Copperwire type:</b>
    <%= @copperwire.copperwire_type %>
  </p>

  <p>
    <b>Self bonded:</b>
    <%= @copperwire.self_bonded %>
  </p>

  <p>
    <b>Diameter:</b>
    <%= @copperwire.diameter %>
  </p>

  <p>
    <b>Drawing norm:</b>
    <%= @copperwire.drawing_norm %>
  </p>

  <p>
    <b>Supplier:</b>
    <%= @copperwire.supplier %>
  </p>

  <p>
    <b>Where used product:</b>
    <%= @copperwire.where_used_product %>
  </p>

  <p>
    <b>Where used plant:</b>
    <%= @copperwire.where_used_plant %>
  </p><br />

  <p>
    <b>Reason for submission:</b>
    <%= @copperwire.reason %>
  </p><br />

  <p>
    <b>Submitted by:</b>
    <%= @copperwire.uploader_name %>
  </p>

  <p>
    <b>Created at:</b>
    <%= @copperwire.created_at %>
  </p>

  <p>
    <b>Last updated at:</b>
    <%= @copperwire.updated_at %>
  </p>
<%= render 'shared/show_actions', :object => @copperwire %>